# Полная эмуляция (вообще без SMTP)
mail.smtp.host=localhost
mail.smtp.port=1025
mail.smtp.auth=false
email.force_emulation=true

# Реальная отправка через Gmail
# email.username=your@gmail.com
# email.password=your_app_password
# email.from=your@gmail.com
# mail.smtp.host=smtp.gmail.com
# mail.smtp.port=587
# mail.smtp.auth=true
# mail.smtp.starttls.enable=true
# email.force_emulation=false

# Тестовый SMTP сервер (MailHog)
# mail.smtp.host=localhost
# mail.smtp.port=1025
# mail.smtp.auth=false
# mail.smtp.starttls.enable=false
# email.from=test@localhost.com
# email.force_emulation=false