# Настройки подключения к SMPP серверу (эмулятору)
smpp.host=localhost
smpp.port=2775
smpp.system_id=smppclient1
smpp.password=password
smpp.system_type=OTP
smpp.source_addr=OTPService

# Режим эмуляции (true - всегда использовать эмуляцию, false - реальная отправка)

smpp.emulation_mode=true